server:
  context: jwt/secure
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learning
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      format_sql: true
      use_sql_comments: true
    show_sql: false
app:
  security:
    jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
    expire: 300000
